spring:
  datasource:
    url: jdbc:h2:mem:myDb?createDatabaseIfNotExist=true&useSSL=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

report:
  owner:
    name: FAISAL