spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: baeldung
    password: baeldung
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        tenant_identifier_resolver: com.faisal.reportgeneratorusingjasper.tenent.CurrentTenantResolver
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

report:
  owner:
    name: FAISAL
